In [1]:
import numpy as np
import pandas as pd

In [7]:
laliga=pd.read_csv('Laliga.csv')

In [8]:
laliga.head(2)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1

In [9]:
laliga.replace('-',0,inplace= True)

In [10]:
laliga.columns=laliga.iloc[0]

In [11]:
laliga.head(2)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1

In [12]:
laliga.columns=laliga.iloc[0]

In [13]:
laliga.drop(0,axis=0,inplace=True)

In [15]:
laliga.head(5)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1

In [16]:
laliga["Debut"]=laliga["Debut"].str.split('-',n=1,expand=True)

In [17]:
laliga.head(5)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931,1987-88,1
5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1

In [31]:
laliga["Debut"]=pd.to_numeric (laliga["Debut"])

In [32]:
laliga.dtypes

0
Pos              object
Team             object
Seasons          object
Points           object
GamesPlayed      object
GamesWon         object
GamesDrawn       object
GamesLost        object
GoalsFor         object
GoalsAgainst     object
Champion         object
Runner-up        object
Third            object
Fourth           object
Fifth            object
Sixth            object
T                object
Debut             int64
Since/LastApp    object
BestPosition     object
dtype: object

In [33]:
laliga.loc[(laliga['Debut']>1929) & (laliga ['Debut']<1981)]

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931,1987-88,1
6,6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,4,4,5,12,6,32,1934,2001-02,1
9,9,Zaragoza,58,2109,1986,698,522,766,2683,2847,0,1,4,5,4,4,18,1939,2012-13,2
10,10,Real Betis,51,1884,1728,606,440,682,2159,2492,1,0,2,3,4,4,14,1932,2015-16,1
11,11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,2188,1,5,4,1,0,1,12,1941,2014-15,1
12,12,Celta Vigo,51,1789,1698,586,389,723,2278,2624,0,0,0,2,4,5,11,1939,2012-13,4
13,13,Valladolid,42,1471,1466,463,384,619,1767,2180,0,0,0,1,1,1,3,1948,2013-14,4
15,15,Sporting Gijon,43,1389,1458,471,358,629,1753,2152,0,1,1,2,2,1,7,1944,2015-16,2
16,16,Osasuna,37,1351,1318,426,327,565,1500,1834,0,0,0,2,2,2,6,1935,2016-17,4
17,17,Malaga,36,1314,1255,390,330,535,1421,1763,0,0,0,1,0,1,2,1949,2008-09,4
18,18,Oviedo,38,1174,1192,408,292,492,1642,1951,0,0,3,2,2,4,11,1933,2000-01,3
19,19,Mallorca,27,1148,988,333,256,399,1182,1371,0,0,2,0,2,1,5,1960,2012-13,3
20,20,Las Palmas,33,1020,1096,367,242,487,1347,1746,0,1,1,1,1,1,5,1951,2015-16,2
22,22,Granada,23,667,742,218,175,349,819,1157,0,0,0,0,0,2,2,1941,2016-17,6
23,23,Rayo Vallecano,17,662,652,189,148,305,760,1088,0,0,0,0,0,0,0,1977,2015-16,8
24,24,Elche,21,606,678,203,180,295,750,1022,0,0,0,0,1,1,2,1959,2014-15,5
26,26,Hercules,20,538,628,184,149,295,716,1050,0,0,0,0,1,4,5,1935,2010-11,5
27,27,Tenerife,13,510,494,155,128,211,619,744,0,0,0,0,2,0,2,1961,2009-10,5
28,28,Murcia,18,445,586,145,143,298,607,992,0,0,0,0,0,0,0,1940,2007-08,11
29,29,Alaves,12,421,380,125,81,174,458,623,0,0,0,0,0,1,1,1930,2016-17,6
30,30,Levante,11,416,402,113,95,194,430,632,0,0,0,0,0,1,1,1963,2015-16,6
31,31,Salamanca,12,375,423,123,102,198,422,581,0,0,0,0,0,0,0,1974,1998-99,7
32,32,Sabadell,14,353,426,129,95,202,492,720,0,0,0,1,1,0,2,1943,1987-88,4
33,33,Cadiz,12,343,448,104,127,217,393,662,0,0,0,0,0,0,0,1977,2005-06,12
35,35,Castellon,11,285,334,103,79,152,419,588,0,0,0,1,2,0,3,1941,1990-91,4
38,38,Cordoba,9,230,282,82,63,137,285,430,0,0,0,0,1,0,1,1962,2014-15,5
40,40,Recreativo,5,188,186,50,46,90,202,296,0,0,0,0,0,0,0,1978,2008-09,8
41,41,Burgos CF,6,168,204,59,50,95,216,310,0,0,0,0,0,0,0,1971,1979-80,12
42,42,Pontevedra,6,150,180,53,44,83,165,221,0,0,0,0,0,0,0,1963,1969-70,7
47,47,Gimnastic,4,91,116,34,16,66,181,295,0,0,0,0,0,0,0,1947,2006-07,7
50,50,Alcoyano,4,76,108,30,16,62,145,252,0,0,0,0,0,0,0,1945,1950-51,10
51,51,Jaen,3,71,90,29,13,48,121,183,0,0,0,0,0,0,0,1953,1957-58,14
53,53,AD Almeria,2,52,68,17,18,33,71,116,0,0,0,0,0,0,0,1979,1980-81,10
55,55,Lleida,2,40,68,13,14,41,70,182,0,0,0,0,0,0,0,1950,1993-94,16
58,58,Condal,1,22,30,7,8,15,37,57,0,0,0,0,0,0,0,1956,1956-57,16
59,59,Atletico Tetuan,1,19,30,7,5,18,51,85,0,0,0,0,0,0,0,1951,1951-52,16
60,60,Cultural Leonesa,1,14,30,5,4,21,34,65,0,0,0,0,0,0,0,1955,1955-56,15

In [36]:
laliga["Points"]=pd.to_numeric (laliga["Points"])

In [39]:
laliga.sort_values ('Points',ascending= False).head(5)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931,1987-88,1
5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1

In [44]:
laliga["GoalsFor"]=pd.to_numeric (laliga["GoalsFor"])

In [45]:
laliga["GoalsAgainst"]=pd.to_numeric (laliga["GoalsAgainst"])

In [41]:
laliga["GamesWon"]=pd.to_numeric (laliga["GamesWon"])
laliga["GamesPlayed"]=pd.to_numeric (laliga["GamesPlayed"])

In [46]:
def Goal_diff_count (a,b):
    diff=a-b
    return (diff)

In [51]:
laliga["Goaldifference"] = laliga.apply (lambda row:Goal_diff_count(row["GoalsFor"],row ["GoalsAgainst"]),axis=1)
print (laliga.reset_index()[["Team","Goaldifference"]])

0                  Team  Goaldifference
0           Real Madrid            2807
1             Barcelona            2786
2       Atletico Madrid            1225
3              Valencia             929
4       Athletic Bilbao             931
5               Sevilla             307
6              Espanyol            -280
7         Real Sociedad              -2
8              Zaragoza            -164
9            Real Betis            -333
10  Deportivo La Coruna            -136
11           Celta Vigo            -346
12           Valladolid            -413
13     Racing Santander            -525
14       Sporting Gijon            -399
15              Osasuna            -334
16               Malaga            -342
17               Oviedo            -309
18             Mallorca            -189
19           Las Palmas            -399
20           Villarreal             103
21              Granada            -338
22       Rayo Vallecano            -328
23                Elche            -272
24               Getafe            -113
25             Hercules            -334
26             Tenerife            -125
27               Murcia            -385
28               Alaves            -165
29              Levante            -202
..                  ...             ...
31             Sabadell            -228
32                Cadiz            -269
33             Logrones            -198
34            Castellon            -169
35             Albacete             -90
36              Almeria            -122
37              Cordoba            -145
38           Compostela             -42
39           Recreativo             -94
40            Burgos CF             -94
41           Pontevedra             -56
42             Numancia             -98
43                Eibar             -28
44               Arenas             -81
45          Real Burgos             -38
46            Gimnastic            -114
47          Extremadura             -55
48               Merida             -45
49             Alcoyano            -107
50                 Jaen             -62
51           Real Union             -31
52           AD Almeria             -45
53               Europa             -34
54               Lleida            -112
55              Leganes             -19
56                Xerez             -28
57               Condal             -20
58      Atletico Tetuan             -34
59     Cultural Leonesa             -31
60               Girona               0

[61 rows x 2 columns]

In [52]:
print ("Max", laliga[["Team","Goaldifference"]][laliga.Goaldifference == laliga.Goaldifference.max()])

Max 0         Team  Goaldifference
1  Real Madrid            2807

In [53]:
print ("Min", laliga[["Team","Goaldifference"]][laliga.Goaldifference == laliga.Goaldifference.min()])

Min 0               Team  Goaldifference
14  Racing Santander            -525

In [56]:
laliga["BestPosition"]=pd.to_numeric (laliga["BestPosition"])

In [59]:
BP = laliga.groupby("BestPosition").agg({"Points":[sum]})
BP

             Points
                sum
BestPosition
1             27933
2              6904
3              5221
4              6563
5              1884
6              2113
7              1186
8              1134
9                96
10              450
11              445
12              511
14               71
15               14
16               81
17              266
19               81
20               34